### PR TITLE
fix on 0.6 and drop 0.4

### PR DESCRIPTION
**Pull request by mlubin**

### CODE REVIEW

**Comment by mlubin** [comment]
CC @leethargo @blegat @yeesian @joaquimg @joehuchette 
A lot of the solver interfaces are now broken on 0.6.

**Comment by joehuchette** [comment]
So escaping behavior for ccall has changed somehow? Do you know the julia PR that discusses this change?






On Fri, Dec 9, 2016 at 10:44 PM -0500, "Miles Lubin" <notifications@github.com> wrote:












Merged #17.

**Comment by mlubin** [comment]
Nothing specific to ccall. There was a longstanding bug with macro hygiene fixed in https://github.com/JuliaLang/julia/pull/15850.

**Comment by blegat** [comment]
Is this the reason JuMP is failing on nightly ?

**Comment by blegat** [comment]
@mlubin How did you notice that this was needed on nightly ? It seems that nightly wasn't failing before the change of the pull request. Isn't it covered by the tests ?

**Comment by mlubin** [comment]
@blegat, it had been broken only very recently on master. I tried it locally.

**Pull request merged**
