### PR TITLE
Add test for bug in ticket #82

### PR DESCRIPTION
**Pull request by blegat**
We should wait that [this ticket](https://projects.coin-or.org/Clp/ticket/82) is fixed before this PR can be merged.

### CODE REVIEW

**Comment by mlubin** [comment]
You'll have better luck reporting the issue on the clp [mailing list](https://list.coin-or.org/mailman/listinfo/clp).

**Comment by blegat** [comment]
Looks like it is fixed on Clp master https://github.com/coin-or/Clp/issues/49#issuecomment-437899246

**Comment by mlubin** [comment]
@blegat Care to update this PR for MOI or close it? Do we have binaries that include the fix?

**Comment by odow** [comment]
@blegat. You are my worst nightmare. The fix for this in Clp introduced a bug which took us a loooong time to track down: https://github.com/JuliaOpt/Clp.jl/pull/77

We can officially close this as fixed on master. And moreover, we have existing tests in MOI that trigger this.

**Pull request closed without merging**
