### PR TITLE
Fix BinaryBuilder static linking in Linux

### LINKED ISSUE #51: Crash from missing symbol
I can reproducibly crash Clp with
```julia
using MathProgBase.SolverInterface, Clp, JLD2, SparseArrays
@load "clpcrash.jld2" data
model = LinearQuadraticModel(ClpSolver())
loadproblem!(model, data...)
optimize!(model)
```
giving the message
```
/home/gunnar/julia1.0/julia: symbol lookup error: /home/gunnar/.julia/packages/Clp/GpVOR/deps/usr/lib/libClp.so: undefined symbol: dgetrf_
```
The 28 MB data file is for now available at http://www.lysator.liu.se/~gunnar/clpcrash.jld2.
```
julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, sandybridge)

(clpcrash) pkg> st -m
    Status `/tmp/clpcrash/Manifest.toml`
  [b99e7846] BinaryProvider v0.5.3
  [e2554f3b] Clp v0.6.1
  [944b1d66] CodecZlib v0.5.1
  [34da2185] Compat v1.4.0
  [864edb3b] DataStructures v0.15.0
  [5789e2e9] FileIO v1.0.5
  [033835bb] JLD2 v0.1.2
  [f8899e07] LinQuadOptInterface v0.6.0
  [b8f27783] MathOptInterface v0.8.1
  [fdba3010] MathProgBase v0.7.7
  [bac558e1] OrderedCollections v1.0.2
  [3bb67fe8] TranscodingStreams v0.8.1
  [2a0f44e3] Base64 
  [ade2ca70] Dates 
  [8bb1440f] DelimitedFiles 
  [8ba89e20] Distributed 
  [b77e0a4c] InteractiveUtils 
  [76f85450] LibGit2 
  [8f399da3] Libdl 
  [37e2e46d] LinearAlgebra 
  [56ddb016] Logging 
  [d6f4376e] Markdown 
  [a63ad114] Mmap 
  [44cfe95a] Pkg 
  [de0858da] Printf 
  [3fa0cd96] REPL 
  [9a3f8284] Random 
  [ea8e919c] SHA 
  [9e88b42a] Serialization 
  [1a1011a3] SharedArrays 
  [6462fe0b] Sockets 
  [2f01184e] SparseArrays 
  [10745b16] Statistics 
  [8dfed614] Test 
  [cf7118a7] UUIDs 
  [4ec0a83e] Unicode 
```

### PR DESCRIPTION
**Pull request by juan-pablo-vielma**
Updates binaries with those from JuliaOpt/ClpBuilder#1 (which fixes missing static linking of libraries in Linux) to fix #51

### CODE REVIEW

**Comment by mlubin** [comment]
What about adding a test for solving an instance where we know that Clp calls lapack?

**Comment by juan-pablo-vielma** [comment]
Yes, I was actually going to propose that. Not sure what the best test would be. Maybe the example from #51 ?

**Comment by juan-pablo-vielma** [comment]
Ok, looks like the right way to test lapack is here: 
https://github.com/coin-or/Clp/blob/aae123d7a3c633a382b7cb9c1f4f78ed6559a10b/Clp/src/ClpMain.cpp#L36-L174
The problems is that coin-lapack does not include the direct c interface (which contains `lapacke.h`), so it will be non-trivial to get Clp to compile with `-DLAPACK_TEST`

**Comment by mlubin** [comment]
No reason to leave this fix unmerged, so I'll open an issue to add the test.

**Pull request merged**
